### ISSUE TITLE
tiny bug report?

### ISSUE THREAD

**Issue by jabiologo** [marquetlab/GCM_compareR#1]
Such a great ShinyApp, very useful, thanks and congrats!

 Probably, here is a small bug:

At the Scenario tab, the option Enter bounding-box coordinates at Study Area: Y coordinates labels are "ymax" both.

https://github.com/marquetlab/GCM_compareR/blob/27e5f41076c78b7ea3dd1d493e59208a8bdbc9de/ui.R#L269

 In Line L269 from ui.R should be:

`numericInput("ymin", "ymin", -60, min = -60, max = 90, step = 0.5)),`

 isn't it?

Cheers

**Comment by marquetlab** [comment]
Thank you it has been solved since
